/*
 * This source file was generated by the Gradle 'init' task
 */
package app;
import app.entity.Person;
import app.io.LoadPeople;
import app.service.PeopleStatistics;
import app.service.PersonStatistics;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.List;

public class App {


    public static void main(String[] args) throws IOException {
        LoadPeople loader = new LoadPeople();
        List<Person> people = loader.load(Paths.get("interndata.ndjson"));
        PersonStatistics.findOldestName(people)
                .ifPresentOrElse(
                        name -> System.out.println("Oldest person: " + name),
                        () -> System.out.println("No data available")
                );
        PeopleStatistics.findAverageAge(people)
                .ifPresentOrElse(
                        age -> System.out.println("Average age of data set: " + age ),
                        () -> System.out.println("No data available")
                );
    }
}
